name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Gardens.json" -e "30149154-fca0eb1b-51f5-48f3-929c-72a9d3e0ce4b" --integration-id "151872-${{ github.run_id }}"
          postman collection run "${{ github.workspace }}/postman/collections/Users.json" -e "30149154-fca0eb1b-51f5-48f3-929c-72a9d3e0ce4b" --integration-id "151872-${{ github.run_id }}"
      - name: Lint API schema using Postman CLI
        run: |
          postman api lint --schema "${{ github.workspace }}/path-to-your-schema-file/openapi-schema.json" --integration-id 151872
  
